basePath: /v1
definitions:
  entity.Person:
    properties:
      age:
        maximum: 127
        minimum: 10
        type: integer
      email:
        type: string
      firstname:
        type: string
      id:
        type: integer
      lastname:
        type: string
    required:
    - email
    - firstname
    - lastname
    type: object
  entity.Video:
    properties:
      author:
        $ref: '#/definitions/entity.Person'
      description:
        maxLength: 25
        type: string
      id:
        type: integer
      title:
        maxLength: 10
        minLength: 3
        type: string
      url:
        example: https://google.com/xyz-video
        type: string
    required:
    - author
    - url
    type: object
host: localhost
info:
  contact:
    email: yintar5@gmail.com
    name: Yinebe T.
    url: www.linkedin.com/in/yinebeb-tariku
  title: hexagonal-architecture
  version: 0.1.0
paths:
  /videos:
    get:
      consumes:
      - application/json
      description: FindAll video description
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Video'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: FindAll video
      tags:
      - Video
    post:
      consumes:
      - application/json
      description: Save video description
      parameters:
      - description: video to save
        in: body
        name: video
        required: true
        schema:
          $ref: '#/definitions/entity.Video'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Video'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Save video
      tags:
      - Video
  /videos/:id:
    delete:
      consumes:
      - application/json
      description: Delete video description
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete video
      tags:
      - Video
    put:
      consumes:
      - application/json
      description: Update video description
      parameters:
      - description: Video ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Video'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update video
      tags:
      - Video
swagger: "2.0"
